# Generated by Django 5.1.3 on 2024-11-19 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('correo', models.EmailField(max_length=64)),
                ('contraseña', models.CharField(max_length=16)),
                ('rol', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('cita_id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('nombre_especialidad', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('horario', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('fecha_nacimiento', models.DateTimeField()),
                ('codigo_uni', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('notificacion_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=256)),
                ('fecha_envio', models.DateTimeField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('horario', models.CharField(max_length=128)),
                ('nombre_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario_medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='usuario_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente'),
        ),
    ]
