# Generated by Django 5.1.3 on 2024-11-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('apellidos', models.CharField(blank=True, max_length=64, null=True)),
                ('correo', models.EmailField(max_length=64)),
                ('contraseña', models.CharField(max_length=16)),
                ('rol', models.CharField(choices=[('Paciente', 'Paciente'), ('Administrador', 'Administrador'), ('Medico', 'Medico')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('cita_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('especialidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_especialidad', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('fecha_nacimiento', models.DateTimeField()),
                ('codigo_uni', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=16)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('notificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=256)),
                ('fecha_envio', models.DateTimeField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especialidad')),
                ('horarios', models.ManyToManyField(to='api.horario')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medico'),
        ),
        migrations.AddField(
            model_name='cita',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente'),
        ),
    ]
