# Generated by Django 5.1.3 on 2024-11-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_contraseña_alter_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='codigo_uni',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Paciente', max_length=16),
        ),
    ]
